version: '3.4'

services:
  chickenpower.backendforfrontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  chickenpower.statesaga:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  chickenpower.pricingproxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44393
    ports:
      - "51422:80"
      - "44393:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  chickenpower.contractgeneratorproxy:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

